language: java
jdk:
    - openjdk13

addons:
    sonarcloud:
        organization: giuseppelasco17
        token: 04ca59b5fa01f7df87d1b20f77e91bd1bb17b5bc
script:
    - ant build
    - sonar-scanner